### ISSUE TITLE
Crash on launch on MacOS 12.1

### ISSUE THREAD

**Issue by TwisterMc** [WoodyLetsCode/WLED-GUI#14]
WLED is crashing when I start the app under MacOS 12.1. 

main.log is pretty light on details.

```
[2022-01-09 17:13:57.356] [info]  WLED-GUI started
[2022-01-09 17:14:01.666] [info]  WLED-GUI started
[2022-01-09 18:03:47.663] [info]  WLED-GUI started
```

[wled-crash-report.txt](https://github.com/WoodyLetsCode/WLED-GUI/files/7836248/wled-crash-report.txt)

**Comment by WoodyLetsCode** [comment]
Hi,
have you made any changes in the settings or does it crash with the default settings?

**Comment by TwisterMc** [comment]
I've been running it for a month or so in which I assume I changed something. This is not a new install.

I can try uninstalling and reinstalling.

**Comment by WoodyLetsCode** [comment]
Yes, please try that first.

**Comment by TwisterMc** [comment]
Everything seems to be working recently so I'm going to close this.
