### ISSUE TITLE
Found Devices Show No Options

### ISSUE THREAD

**Issue by azurusnova** [WoodyLetsCode/WLED-GUI#21]
**Describe the bug**
When bringing up the GUI window, I can detect and find all the devices on my network, but when selecting any of them, nothing but a blank window shows up. I was able to get a crash log from my Linux Mint system to help further looking into this bug. 

**To Reproduce**
1. Run WLED GUI on a Linux Mint 21.1 install. 
2. Click on a found WLED device on the network. 
3. No options shown in the window for selected device. 

**Expected behavior**
Options for said selected device should show up and be operable.

**Screenshots**
First image shows the devices on my network. 
![image](https://user-images.githubusercontent.com/30223722/212295351-4eb5f40d-4379-4a87-b158-e64aa540a53f.png)
But when selecting any of them, this is all I am given. 
![image](https://user-images.githubusercontent.com/30223722/212295458-4f9f178c-5577-47d7-b198-7557a3568991.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint Cinnamon
 - Version 21.1

**Additional context**
Here is a pastebin of the crash report from my system given about the WLED GUI bug.
https://termbin.com/ph0v

If the link does not work, Ill copy it below.

===================================================================
 Info                                                              
===================================================================
           PID: 2423 (wled-gui)
           UID: 1000 (azurusnova)
           GID: 1000 (azurusnova)
        Signal: 31 (SYS)
     Timestamp: Fri 2023-01-13 01:56:55 PST (5min ago)
  Command Line: $'/opt/WLED/wled-gui --type=renderer --field-trial-handle=16358194044287095488,15556290221622830441,131072 --enable-features=WebComponentsV0Enabled --disable-features=CertVerifierService,CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --lang=en-US --app-path=/opt/WLED/resources/app.asar --enable-sandbox --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=7 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100'
    Executable: /opt/WLED/wled-gui
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (azurusnova)
       Boot ID: a289d9df7445484eb69508659b0dd76f
    Machine ID: e7d0df732b0649e49e97a4d764308014
      Hostname: azurusnova
       Storage: /var/lib/systemd/coredump/core.wled-gui.1000.a289d9df7445484eb69508659b0dd76f.2423.1673603815000000.zst (present)
     Disk Size: 1.6M
       Message: Process 2423 (wled-gui) of user 1000 dumped core.
                
                Found module linux-vdso.so.1 with build-id: dba798e3849739247caa8c4b4acc15cf5f1b3c88
                Found module libresolv.so.2 with build-id: 7fd7253c61aa6fce2b7e13851c15afa14a5ab160
                Found module libkeyutils.so.1 with build-id: ff27227afa5eeddccab180dd29bd7fcff94aea7c
                Found module libmd.so.0 with build-id: cd2d2f71b3967ebde30e2aa43b8eb63339020c06
                Found module libbrotlicommon.so.1 with build-id: 43a72967cf84155914c8b3e915926733d1e57c11
                Found module libgpg-error.so.0 with build-id: 3fbec71c67bee60d8aef00697ee187079b0fb307
                Found module libgmp.so.10 with build-id: f110719303ddbea25a5e89ff730fec520eed67b0
                Found module libhogweed.so.6 with build-id: 3cc4a3474de72db89e9dcc93bfb95fe377f48c37
                Found module libnettle.so.8 with build-id: 3d9c6bf106ef53d625b7b1c8bb1300e84598a74a
                Found module libtasn1.so.6 with build-id: 2fde6ecb43c586fe4077118f771077aa1298e7ea
                Found module libunistring.so.2 with build-id: ca5149da8d5a298b8f286ffca3d6e2402ec0fe01
                Found module libidn2.so.0 with build-id: 45b73e0e1c46a76be22f572ee98c60af5768bf8f
                Found module libp11-kit.so.0 with build-id: a0ffe1d002de5812dc718186172efb78604ddf2c
                Found module libkrb5support.so.0 with build-id: f9dcbdef069078853fc0d3d7fbfc9bbb923cfe3c
                Found module libcom_err.so.2 with build-id: ce0901f10854b3c9276066b98d9a72303206e0d5
                Found module libk5crypto.so.3 with build-id: 1b22be74b69ba5fcd325664ba47bf9e87bf7d530
                Found module libkrb5.so.3 with build-id: c840d413c769ab9bcbcd12740eca61e5a969cce3
                Found module libbsd.so.0 with build-id: 9a6c72469251e2feb63e175ef5cb944ce6e00df3
                Found module libbrotlidec.so.1 with build-id: 4b1f390dd6e24d49684db8b2443d082379e8e977
                Found module libdatrie.so.1 with build-id: 128b6874a47f2b783d9e9060d3caaee4110bfd3d
                Found module libuuid.so.1 with build-id: 64c0d0cb22fa2bdeca075a0c0418ba5ff314b220
                Found module libgraphite2.so.3 with build-id: 5ffbc76fc948f6b88d766a7210c2e6a329a6c278
                Found module libgcrypt.so.20 with build-id: 60a5e524de0ed8323edf33e9eb9127a9eee02359
                Found module libcap.so.2 with build-id: 9e11e3bca4b0a25d047cb36e933e1d727663cf8e
                Found module liblz4.so.1 with build-id: a85971851cd059f1af80d553c8e7170d42ec59a1
                Found module libzstd.so.1 with build-id: 5d9d0d946a3154a748e87e17af9d14764519237b
                Found module liblzma.so.5 with build-id: b85da6c48eb60a646615392559483b93617ef265
                Found module libpcre2-8.so.0 with build-id: 184a841c55fb7fe5e3873fcda8368c71016cd54c
                Found module libblkid.so.1 with build-id: cdf95a964e3302bb356fefc4b801fae8c4340b31
                Found module libgnutls.so.30 with build-id: b9fa7b6d0c47adb8a3f03b2452c3df3eb2c93715
                Found module libavahi-client.so.3 with build-id: bfe4357823739cfde10dbc3a40971c391bee9c41
                Found module libavahi-common.so.3 with build-id: 5e23004fad8b0b7f921dcff3df5f9855904f45d2
                Found module libgssapi_krb5.so.2 with build-id: cfb0a0611861784ae85210cca6e5cc729e554c23
                Found module libstdc++.so.6 with build-id: f57e02bfadacc0c923c82457d5e18e1830b5faea
                Found module libwayland-server.so.0 with build-id: 75c4598a62c3c6e94868467866488cdfba049e7d
                Found module libXdmcp.so.6 with build-id: 6b60f99504aa1d3999ea02a14366d1a39d6c5dcf
                Found module libXau.so.6 with build-id: 7089b383cacbfc1760634a3be19a923e51fe3315
                Found module libXrender.so.1 with build-id: 7ccbfa4c24e93c42fa50dd2e42fa277630f9650c
                Found module libxcb-render.so.0 with build-id: cb521131fd3b0f2ee6056cbc2014b3b8ef0d5c0e
                Found module libxcb-shm.so.0 with build-id: edb24ef4079aa423edcc50a3bb0dfb912fe8a57a
                Found module libfreetype.so.6 with build-id: e3aff1d56fb1aecc723a73882f7d0f208a36c4bc
                Found module libpixman-1.so.0 with build-id: 5e936cdac032b6048d9d1a8c0bb0e4a10c86d48c
                Found module libthai.so.0 with build-id: afa54530349e68380815d606d15dbfda8952799f
                Found module libwayland-client.so.0 with build-id: a85980f4efa33fa5cadfbf257349fef99d499427
                Found module libwayland-egl.so.1 with build-id: e13dfac5961e8fb58c54984fe8110a73c2f5ef99
                Found module libwayland-cursor.so.0 with build-id: abcd1ab467757354ac36fd0938b82d47d7aebe1f
                Found module libXcursor.so.1 with build-id: d936a5db46d8babb0f2cc490df36b6b18a16d8aa
                Found module libXinerama.so.1 with build-id: 9823bebfa26a681265db4aeb09abf44deec38401
                Found module libfontconfig.so.1 with build-id: 0bb435fdd5ec37178e14ea03bb36f779a4b72a94
                Found module libharfbuzz.so.0 with build-id: 3b9c495c079286b8d1f55d0937a0a771593eb7e6
                Found module libpangoft2-1.0.so.0 with build-id: a7dd79c7ea8ec4d5791f83f9a8f34ffbfa8c3801
                Found module libfribidi.so.0 with build-id: 6e075a666e1da8ffdb948d734e75d82b1b6dc0fb
                Found module libepoxy.so.0 with build-id: 5ea53a2b100e4b044eee19d5222881a724abf046
                Found module libcairo-gobject.so.2 with build-id: 71b5bd37d77ea1862d2ed00e9f6ead482f307db8
                Found module libXi.so.6 with build-id: 8ff5a3ac871a90fd9d0a7917c61f748a41c6b5ee
                Found module libpangocairo-1.0.so.0 with build-id: cb231e62ccba07e561d1d08804e975f615a6faf6
                Found module libjpeg.so.8 with build-id: c54abff9294357e28532a76a049a4cb2542fc15b
                Found module libpng16.so.16 with build-id: d58bf7c11ac793d528926238d831792b5ef792cf
                Found module libsystemd.so.0 with build-id: 61fb1ea64197576f79977fb27e1be39a088e7f3e
                Found module libplds4.so with build-id: 7a42de24ba93c1411714c1bf4179f213861ca88d
                Found module libplc4.so with build-id: 5a402ce5ec0224c4d29815c4e15334d92f6ecf05
                Found module libselinux.so.1 with build-id: 6fa53202ce676297de24873c886443b2759bfd8a
                Found module libmount.so.1 with build-id: eeb33f2b4b9c3eb0a29575eb9932ef08663bd836
                Found module libz.so.1 with build-id: 30840b79ac329ecbf1dec0bb60180eed256d319f
                Found module libgmodule-2.0.so.0 with build-id: 991a9f61e69c30ef8ab73761c300ae51249ede63
                Found module libpcre.so.3 with build-id: 3982f316c887e3ad9598015fa5bae8557320476a
                Found module libffi.so.8 with build-id: 59c2a6b204f74f358ca7711d2dfd349d88711f6a
                Found module ld-linux-x86-64.so.2 with build-id: 61ef896a699bb1c2e4e231642b2e1688b2f1a61e
                Found module libc.so.6 with build-id: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d
                Found module libgcc_s.so.1 with build-id: 09c4935b79388431a1248f6a98e00d7dc81b8513
                Found module libatspi.so.0 with build-id: 2843c68233d5ba81da3d6bc31422e49472873dba
                Found module libcups.so.2 with build-id: d3f64a3ab859de045e124a0271356296fa446150
                Found module libasound.so.2 with build-id: d1986cd985564afaa9aa64c753423b01dd5b228e
                Found module libgbm.so.1 with build-id: bf1b52367ee353eee83b42a4e2e0486d67f1c0e2
                Found module libxkbcommon.so.0 with build-id: a4b17d939092101dc8f6b2a1d70eaf1fddb2dd51
                Found module libxcb.so.1 with build-id: 1bef862a339557aa16c34c7a4b27f8f3aea90517
                Found module libexpat.so.1 with build-id: d212d1f61d04a1e60fccad1a8c118428cfd9be42
                Found module libXrandr.so.2 with build-id: 069f930a2b41f3908a1a92b1a51c38bd13a559e2
                Found module libXfixes.so.3 with build-id: a9c550a40b8154a3b4b5e2ac182bb50c013c3f18
                Found module libXext.so.6 with build-id: 9fb1880e02dfa11a8c39cd1a170109de08302059
                Found module libXdamage.so.1 with build-id: 8358b7625700dc247fa21fb4304cba877a28bb04
                Found module libXcomposite.so.1 with build-id: 2c84db5342304ba1a76db7dd9b7a3bfaa8a716ce
                Found module libX11.so.6 with build-id: b8d9314a7185312e4813abcac67d8b68ae2fd690
                Found module libm.so.6 with build-id: 27e82301dba6c3f644404d504e1bb1c97894b433
                Found module libcairo.so.2 with build-id: 60a39c3684e41370bd0a59ed1ecbdccf47e30069
                Found module libpango-1.0.so.0 with build-id: 2d778a30dd59c0673b0208c538999ccc0991093a
                Found module libgdk-3.so.0 with build-id: 97b768ef80858a79741be2492754d948989e63c6
                Found module libgtk-3.so.0 with build-id: 9a340345f5e200f42140f3cb4bacb407e91843f8
                Found module libgdk_pixbuf-2.0.so.0 with build-id: 374b383e3b68b5d8b552519094129f401596e502
                Found module libdrm.so.2 with build-id: d32defdcdf5f200f16d1633e52372f5e158f64a5
                Found module libdbus-1.so.3 with build-id: 63e8b99215502138cb63afd6d65851a5e837ed49
                Found module libatk-bridge-2.0.so.0 with build-id: 7e8009077fbdcd7bf094c51bf78742b96f216d73
                Found module libatk-1.0.so.0 with build-id: b93088667fbd06f6b72d273403d352e7c0554698
                Found module libnspr4.so with build-id: e3e4d4d1a1147e472eccb52c81c7900edd363c43
                Found module libsmime3.so with build-id: 292adbee233a91d925fd9ee6383937642dfabd74
                Found module libnssutil3.so with build-id: b24a1ca29f12cf954fe008d91fdb385f813cce7f
                Found module libnss3.so with build-id: 8b792587a5804b3f7a31761a10d2b45fdfed054b
                Found module libgio-2.0.so.0 with build-id: 9b52271b63917542ba10ffb8a82b97befd2c238f
                Found module libxshmfence.so.1 with build-id: f08296172ec7b676e1b371afc936e36add17366d
                Found module libglib-2.0.so.0 with build-id: 137458a0f7846a084270bf5bb03df075a578db6d
                Found module libgobject-2.0.so.0 with build-id: 44f60e584780daaeb1880ead5dd00f12ffd423d2
                Found module librt.so.1 with build-id: 1030be4690f8aa93b63acd9180b3037d99a974bf
                Found module libpthread.so.0 with build-id: e62798b68557abb4bc5548aba2640cd5ab948f36
                Found module libdl.so.2 with build-id: 952123c3bdce7c3370553717942b4878d1fad797
                Found module libffmpeg.so with build-id: 13070cd6d4401903dee7a42e402d150de4362b18
                Found module wled-gui with build-id: 50300d22dcba520f8681cbf4f8bd71ff9320371c
                Stack trace of thread 1:
                #0  0x00007f99924909ed __clone3 (libc.so.6 + 0x1269ed)
===================================================================
 GDB Log                                                           
===================================================================

warning: Can't open file /dev/shm/.org.chromium.Chromium.D6WhRH (deleted) during file-backed mapping note processing
[New LWP 1]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/opt/WLED/wled-gui --type=rendere'.
Program terminated with signal SIGSYS, Bad system call.
#0  clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:62
62	../sysdeps/unix/sysv/linux/x86_64/clone3.S: No such file or directory.

===================================================================
 GDB Backtrace                                                     
===================================================================

warning: Can't open file /dev/shm/.org.chromium.Chromium.D6WhRH (deleted) during file-backed mapping note processing
[New LWP 1]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/opt/WLED/wled-gui --type=rendere'.
Program terminated with signal SIGSYS, Bad system call.
#0  clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:62
62	../sysdeps/unix/sysv/linux/x86_64/clone3.S: No such file or directory.
#0  clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:62
#1  0x00007f9992490a51 in __GI___clone_internal (cl_args=cl_args@entry=0x7fff6f1756e0, func=func@entry=0x7f99923fe850 <start_thread>, arg=arg@entry=0x7f998f941640) at ../sysdeps/unix/sysv/linux/clone-internal.c:54
#2  0x00007f99923fe759 in create_thread (pd=pd@entry=0x7f998f941640, attr=attr@entry=0x7fff6f175a70, stopped_start=stopped_start@entry=0x7fff6f1757fe, stackaddr=stackaddr@entry=0x7f998f141000, stacksize=8386688, thread_ran=thread_ran@entry=0x7fff6f1757ff) at ./nptl/pthread_create.c:295
#3  0x00007f99923ff280 in __pthread_create_2_1 (newthread=<optimized out>, attr=<optimized out>, start_routine=<optimized out>, arg=<optimized out>) at ./nptl/pthread_create.c:828
#4  0x000055b7e45ca44b in ?? ()
#5  0x000017a12d867be0 in ?? ()
#6  0x00007f998f941640 in ?? ()
#7  0x00007fff6f1759b0 in ?? ()
#8  0x000017a12d6f2c80 in ?? ()
#9  0x0000000000000030 in ?? ()
#10 0x000017a12d84cbb8 in ?? ()
#11 0x00007fff6f175970 in ?? ()
#12 0x000055b7e9c95c85 in __start_google_malloc ()
#13 0x000055b7e4a60d74 in ?? ()
#14 0x00007fff6f175b30 in ?? ()
#15 0x0000000000000000 in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================

warning: Can't open file /dev/shm/.org.chromium.Chromium.D6WhRH (deleted) during file-backed mapping note processing
[New LWP 1]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/opt/WLED/wled-gui --type=rendere'.
Program terminated with signal SIGSYS, Bad system call.
#0  clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:62
62	../sysdeps/unix/sysv/linux/x86_64/clone3.S: No such file or directory.

Thread 1 (Thread 0x7f9990e313c0 (LWP 1)):
#0  clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:62
No locals.
#1  0x00007f9992490a51 in __GI___clone_internal (cl_args=cl_args@entry=0x7fff6f1756e0, func=func@entry=0x7f99923fe850 <start_thread>, arg=arg@entry=0x7f998f941640) at ../sysdeps/unix/sysv/linux/clone-internal.c:54
        ret = <optimized out>
        saved_errno = 1
        flags = <optimized out>
        stack = <optimized out>
#2  0x00007f99923fe759 in create_thread (pd=pd@entry=0x7f998f941640, attr=attr@entry=0x7fff6f175a70, stopped_start=stopped_start@entry=0x7fff6f1757fe, stackaddr=stackaddr@entry=0x7f998f141000, stacksize=8386688, thread_ran=thread_ran@entry=0x7fff6f1757ff) at ./nptl/pthread_create.c:295
        need_setaffinity = <optimized out>
        clone_flags = 4001536
        tp = 0x7f998f941640
        args = {flags = 4001536, pidfd = 140297515571472, child_tid = 140297515571472, parent_tid = 140297515571472, exit_signal = 0, stack = 140297507180544, stack_size = 8386688, tls = 140297515570752, set_tid = 0, set_tid_size = 0, cgroup = 0}
        ret = <optimized out>
        __PRETTY_FUNCTION__ = "create_thread"
#3  0x00007f99923ff280 in __pthread_create_2_1 (newthread=<optimized out>, attr=<optimized out>, start_routine=<optimized out>, arg=<optimized out>) at ./nptl/pthread_create.c:828
        stackaddr = 0x7f998f141000
        stacksize = <optimized out>
        iattr = 0x7fff6f175a70
        default_attr = {external = {__size = "\250X\027o\377\177\000\000@\002\000\000\000\000\000\000\200X\027o\377\177\000\000\225\313\266\343\267U\000\000\200X\027o\377\177\000\000\200\000\000\000\000\000\000\000\017\002\000\000\000\000\000", __align = 140735057189032}, internal = {schedparam = {sched_priority = 1863801000}, schedpolicy = 32767, flags = 576, guardsize = 140735057188992, stackaddr = 0x55b7e3b6cb95, stacksize = 140735057188992, extension = 0x80, unused = 0x20f}}
        destroy_default_attr = <optimized out>
        c11 = <optimized out>
        pd = 0x7f998f941640
        err = 0
        retval = 0
        self = <optimized out>
        stopped_start = false
        thread_ran = false
        original_sigmask = {__val = {0, 6442450944, 4, 27968, 2, 736, 25981019434112, 140735057189016, 140735057189088, 94248311895703, 94248395070880, 25981020677184, 25981020676608, 25981019434112, 16, 1}}
        __PRETTY_FUNCTION__ = "__pthread_create_2_1"
#4  0x000055b7e45ca44b in ?? ()
No symbol table info available.
#5  0x000017a12d867be0 in ?? ()
No symbol table info available.
#6  0x00007f998f941640 in ?? ()
No symbol table info available.
#7  0x00007fff6f1759b0 in ?? ()
No symbol table info available.
#8  0x000017a12d6f2c80 in ?? ()
No symbol table info available.
#9  0x0000000000000030 in ?? ()
No symbol table info available.
#10 0x000017a12d84cbb8 in ?? ()
No symbol table info available.
#11 0x00007fff6f175970 in ?? ()
No symbol table info available.
#12 0x000055b7e9c95c85 in __start_google_malloc ()
No symbol table info available.
#13 0x000055b7e4a60d74 in ?? ()
No symbol table info available.
#14 0x00007fff6f175b30 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.
#0  clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:62
#1  0x00007f9992490a51 in __GI___clone_internal (cl_args=cl_args@entry=0x7fff6f1756e0, func=func@entry=0x7f99923fe850 <start_thread>, arg=arg@entry=0x7f998f941640) at ../sysdeps/unix/sysv/linux/clone-internal.c:54
#2  0x00007f99923fe759 in create_thread (pd=pd@entry=0x7f998f941640, attr=attr@entry=0x7fff6f175a70, stopped_start=stopped_start@entry=0x7fff6f1757fe, stackaddr=stackaddr@entry=0x7f998f141000, stacksize=8386688, thread_ran=thread_ran@entry=0x7fff6f1757ff) at ./nptl/pthread_create.c:295
#3  0x00007f99923ff280 in __pthread_create_2_1 (newthread=<optimized out>, attr=<optimized out>, start_routine=<optimized out>, arg=<optimized out>) at ./nptl/pthread_create.c:828
#4  0x000055b7e45ca44b in ?? ()
#5  0x000017a12d867be0 in ?? ()
#6  0x00007f998f941640 in ?? ()
#7  0x00007fff6f1759b0 in ?? ()
#8  0x000017a12d6f2c80 in ?? ()
#9  0x0000000000000030 in ?? ()
#10 0x000017a12d84cbb8 in ?? ()
#11 0x00007fff6f175970 in ?? ()
#12 0x000055b7e9c95c85 in __start_google_malloc ()
#13 0x000055b7e4a60d74 in ?? ()
#14 0x00007fff6f175b30 in ?? ()
#15 0x0000000000000000 in ?? ()

**Comment by azurusnova** [comment]
For the time being I have uninstalled the app since every time my system would crash while I am gaming, that would be the only app that would show up in the crash log in my Mint system.

**Comment by WoodyLetsCode** [comment]
Hi! Thank you for the report?
What WLED version do you use?
Does it work if you enable online Mode in settings?

**Comment by azurusnova** [comment]
> Hi! Thank you for the report! What WLED version do you use? Does it work if you enable online Mode in settings?

Using the latest version that I can get from here on the site.
I havent tried the online mode in settings, cant at the moment since I am trying to suss out another issue of my whole system crashing out while playing a game after my GPU upgrade. Trying to update the BIOS to see if that problem is sussed out. 

I still don't know why I can't reply without it closing out the issue, I don't want to close it out. It only gives these two options for me when trying to reply. 
![image](https://user-images.githubusercontent.com/30223722/212333433-ee4bd7b4-c9e2-4bbd-84a3-f486897b467d.png)

**Comment by WoodyLetsCode** [comment]
I meant which WLED version do your lights have?
You can see the version if you click on info here:
![grafik](https://user-images.githubusercontent.com/27882680/212334962-f082bbbe-993e-4fe6-85f7-e87bdb5a57c2.png)

**Comment by azurusnova** [comment]
> I meant which WLED version do your lights have? You can see the version if you click on info here: ![grafik](https://user-images.githubusercontent.com/27882680/212334962-f082bbbe-993e-4fe6-85f7-e87bdb5a57c2.png)

![image](https://user-images.githubusercontent.com/30223722/212344669-9bc2234c-af05-4c6e-9b32-cd5809f978b1.png)
Had to pull this from my phone since those options do not even come up in the UI.

**Comment by WoodyLetsCode** [comment]
It is probably because of the WLED version 0.14.
WLED-GUI does not support this version right now completely.
But I think it would work if you enable online mode for the devices with this version in WLED-GUI settings.

**Comment by azurusnova** [comment]
Tried setting one of the lamps toggles to online mode and it didn't change anything for it. 

Sorry for the late reply, had to debug a crashing system after a GPU upgrade (ended up being the power supply).

I will be keeping closer tabs and hoping for a possible upgrade. 
Thank you though for all your work on making WLED much better through this. 

On a note, I did try an older version of the program as you suggested to someone else having the same issue on a windows machine, while it did kind of work, it wasnt ideal.

**Comment by WoodyLetsCode** [comment]
I will try to reproduce and fix this, maybe in March.
Sorry for that, but I have to do a lot of other stuff right now. 😞

**Comment by azurusnova** [comment]
No pressure. I am glad that I could spot this issue and provide the information I have. 
 I'll be following along as you go.

**Comment by WoodyLetsCode** [comment]
How did you install WLED? The latest release is 0.14.0-b1. How did you install 0.14.0.2.1?
Have you tried it with using the latest release from here?
https://github.com/Aircoookie/WLED/releases

**Comment by azurusnova** [comment]
> How did you install WLED? The latest release is 0.14.0-b1. How did you install 0.14.0.2.1? Have you tried it with using the latest release from here? https://github.com/Aircoookie/WLED/releases

Sorry about the long delay. 

Ive been having this issue with all versions of WLED, the normal version and even the Moon Mod version. 
Ive installed them with ESP-Flasher, https://install.wled.me/ and even using the over the air option on each board.

**Comment by azurusnova** [comment]
Damn close option, wish that wasnt the default. lol

**Comment by WoodyLetsCode** [comment]
Just to be sure: Does only the settings page not work in WLED-GUI or does the whole WLED Page not show up?

**Comment by azurusnova** [comment]
When staring up the app, the lights show up in the list, but anytime I click on one and go to the gui for the lights, its all blank. 
![image](https://user-images.githubusercontent.com/30223722/230825502-a0aa624a-3e8e-4ed8-9b07-de6a65c604a5.png)
This is what I should see from my lights. 
(this is a screenshot from the browser.)
![image](https://user-images.githubusercontent.com/30223722/230825651-4b21b1ba-be25-487d-abf1-7b79d6bbf83f.png)
This is what I see here from the app.

**Comment by azurusnova** [comment]
/home/azurusnova/Videos/2023-04-17-02:56:01.187469660.mkv
Here's a video clip of what I am encountering, if that would help make sense of what I am dealing with.

**Comment by WoodyLetsCode** [comment]
Thank you for the video! I have to look into this again and try to reproduce it.

**Comment by azurusnova** [comment]
I was wondering if you have ever found a fix.

**Comment by WoodyLetsCode** [comment]
Hi!
To be honest, I haven't tried to reproduce it, and seeing that you created this issue over a year ago makes me feel a little sad for you. I wasn't very motivated to fix it because I would have had to set up Linux Mint as well.
Unfortunately, I won't be able to fix it until March. I know I already said this last year, but I have enough to do at the moment with WLED and other things. 😞 
Maybe there is somebody who wants to fix this and make a pull request. Otherwise, I'll have to look into it. But I don't want to make any empty promises. Let's see if I get around to it this time.

**Comment by azurusnova** [comment]
Don't worry about the timeline. I am patient. :P

Also I tried installing the latest version onto another Mint computer and got the same results. 
I am starting to think that this could be a chrome issue if this is what it is running on as a backend.

**Comment by voidnullvalue** [comment]
> Don't worry about the timeline. I am patient. :P
> 
> Also I tried installing the latest version onto another Mint computer and got the same results. I am starting to think that this could be a chrome issue if this is what it is running on as a backend.

I am a little late to the party, but I experienced the same issue on Ubuntu Studio. 
as a temporary workaround, you can call the application via CLI with the --no-sandbox flag it should make it function. I submitted a PR that fixes the issue on Ubuntu Studio, it should work on other Ubuntu derivatives as well.
