### ISSUE TITLE
No Icon

### ISSUE THREAD

**Issue by xRealNeon** [WoodyLetsCode/WLED-GUI#6]
**Describe the bug**
The application has no icon on Linux

**To Reproduce**
Just installed

**Screenshots**
![grafik](https://user-images.githubusercontent.com/20997346/104568183-0a976b00-5650-11eb-9926-98c8858e5514.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 
 - Version 20.04.1 LTS

**Comment by WoodyLetsCode** [comment]
Hey,
thank you for reporting! I will check that.
I will write you back if I have a solution.

**Comment by WoodyLetsCode** [comment]
I will probably publish a new release this weekend where this is fixed.

**Comment by WoodyLetsCode** [comment]
Hey,
i have published [version 0.7.0](https://github.com/WoodyLetsCode/WLED-GUI/releases/tag/v0.7.0).
Could you please tell me if this has fixed your issue?
